name: go

on:
  push:
  pull_request:
    types: [opened]

jobs:
  go:
    runs-on: ubuntu-latest
    name: go
    steps:
      - uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: go dependencies
        run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.38.0
          go mod download

      - name: lint
        run: |
          golangci-lint run

      - name: test
        run: |
          go test -v ./...

